solution:
  name: ciat
  projects:
    launcher:
      name: ciatLauncher
      type: console
      framework: net9.0
      packages:
        - name: Microsoft.CodeAnalysis
          version: 4.12.0
        - name: Microsoft.CodeAnalysis.CSharp
          version: 4.12.0
        - name: System.CommandLine
          version: 2.0.0-beta4.22272.1
        - name: YamlDotNet
          version: 16.3.0
    command:
      name: ciatCommand
      type: classlib
      framework: net9.0
    subProjects: # List of sub-projects (added by the user)
      - name: sample
        type: classlib
        framework: net9.0