
name: wc-sample

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of runner to use for the job. It can be windows-latest, ubuntu-latest or macos-latest.
        required: true
        type: string

jobs:
  sample-command:
    runs-on: ${{inputs.runs-on}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ciat

      - name: Set ciatLauncher path
        id: ciat-launcher
        shell: python
        run: |
          import os

          if "${{runner.os}}" == "Windows":
            path = "ciat/ciatLauncher.exe"
          else:
            path = "ciat/ciatLauncher"

          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"path={path}\n")

      - name: Make executable (linux)
        if: ${{runner.os == 'Linux'}}
        run: chmod +x ${{steps.ciat-launcher.outputs.path}}

      - name: Execute SampleEmpty command
        run: ${{steps.ciat-launcher.outputs.path}} SampleEmpty

      - name: Execute SampleLogger command
        run: ${{steps.ciat-launcher.outputs.path}} SampleLogger

      - name: Execute SampleProperties command
        run: >
          ${{steps.ciat-launcher.outputs.path}} SampleProperties
          --ByteProperty 255
          --SByteProperty -128
          --ShortProperty -32768
          --UShortProperty 65535
          --IntProperty 2147483647
          --UIntProperty 4294967295
          --LongProperty -9223372036854775808
          --ULongProperty 18446744073709551615
          --FloatProperty 3.14
          --DoubleProperty 2.718
          --DecimalProperty 1.618
          --BoolProperty true
          --CharProperty A
          --StringProperty "Hello world ciat!"