
name: wc-sample

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of runner to use for the job. It can be windows-latest, ubuntu-latest or macos-latest.
        required: true
        type: string

jobs:
  sample-command:
    runs-on: ${{inputs.runs-on}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ciat

      - name: Make executable (linux)
        if: ${{runner.os == 'Linux'}}
        run: chmod +x ciatLauncher

      - name: Execute SampleEmpty command
        run: ciatLauncher SampleEmpty

      - name: Execute SampleLogger command
        run: ciatLauncher SampleLogger

      - name: Execute SampleProperties command
        run: >
          ciatLauncher SampleProperties
          --ByteProperty 255
          --SByteProperty -128
          --ShortProperty -32768
          --UShortProperty 65535
          --IntProperty 2147483647
          --UIntProperty 4294967295
          --LongProperty -9223372036854775808
          --ULongProperty 18446744073709551615
          --FloatProperty 3.14
          --DoubleProperty 2.718
          --DecimalProperty 1.618
          --BoolProperty true
          --CharProperty A
          --StringProperty "Hello world ciat!"